export const colors = {
  primary: '#FF7A1A',
  primaryLight: '#FF9B3D',
  primarySoft: '#FFC27A',
  primaryPale: '#FFEDD8',
  background: '#FFF9F3',
  gradientStart: '#F97B1F',
  gradientEnd: '#FFB067',
  white: '#FFFFFF',
  black: '#1A1A1A',
  textPrimary: '#2B2B2B',
  textSecondary: '#7A7A7A',
  textMuted: '#A8A8A8',
  border: '#EFE6DC',
  card: '#FFFFFF',
  danger: '#E4483F',
  dangerLight: '#FBD9D6',
  warning: '#F5A623',
  warningLight: '#FCEBC7',
  success: '#4CAF50',
  successLight: '#DCF3DD',
  disabled: '#E0E0E0',
};

export default colors;
